name: ubuntu
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      OF_URL: https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_linux64gcc6_release.tar.gz
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: mkdir .ofxPiMapper
      - run: mv ./* .ofxPiMapper/
      - run: wget ${OF_URL} --tries=10 --quiet
      - run: |
          OF_ARCHIVE_NAME=$(basename -- "$OF_URL")
          tar -xf ${OF_ARCHIVE_NAME}
          rm ${OF_ARCHIVE_NAME}
          OF_EXTRACT_NAME=$(basename ${OF_ARCHIVE_NAME} .tar.gz)
          mv ${OF_EXTRACT_NAME} openFrameworks
      - run: mv .ofxPiMapper openFrameworks/addons/ofxPiMapper
      - run: |
          cd openFrameworks/scripts/linux/ubuntu
          sudo ./install_dependencies.sh -y
      - run: |
          cd openFrameworks/scripts/linux
          ./compileOF.sh
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_basic
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_camera
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_fbo-sources
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_gamepad
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_pocketvj
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_remote-client
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_remote-server
          mv addons.make.norpi addons.make && make
      - run: |
          cd openFrameworks/addons/ofxPiMapper/example_simpler
          mv addons.make.norpi addons.make && make
