name: ubuntu
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      OF_URL: https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_linux64gcc6_release.tar.gz
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: mkdir .ofxPiMapper
      - run: mv ./* .ofxPiMapper/
      - run: wget -O openFrameworks.tar.gz ${OF_URL} --tries=10 --quiet
      - run: tar -xf openFrameworks.tar.gz && rm openFrameworks.tar.gz
      - run: mv .ofxPiMapper openFrameworks/addons/ofxPiMapper
      - run: |
          echo "Install openFrameworks Dependencies"
          cd openFrameworks/scripts/linux/ubuntu
          sudo ./install_dependencies.sh -y
      - run: |
          echo "Compile openFrameworks"
          cd openFrameworks/scripts/linux
          ./compileOF.sh
      - run: |
          echo "Compile ofxPiMapper/example_basic"
          cd openFrameworks/addons/ofxPiMapper/example_basic
          mv addons.make.norpi addons.make
          make
