name: windows
on:
  push:
    branches:
      - windows-workflow
jobs:
  compile:
    runs-on: windows-latest
    env:
      OF_URL: https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_msys264_release.zip
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel git
          msystem: MINGW64
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download openFrameworks and add ofxPiMapper to addons
        run: |
          mkdir .ofxPiMapper
          mv ./* .ofxPiMapper/
          wget ${OF_URL} --tries=10 --quiet
          echo "Unarchive openFrameworks"
          OF_ARCHIVE_NAME=$(basename -- "$OF_URL")
          tar -xf ${OF_ARCHIVE_NAME}
          rm ${OF_ARCHIVE_NAME}
          OF_EXTRACT_NAME=$(basename ${OF_ARCHIVE_NAME} .tar.gz)
          mv ${OF_EXTRACT_NAME} openFrameworks
          mv .ofxPiMapper openFrameworks/addons/ofxPiMapper
      - name: Install openFrameworks Dependencies
        working-directory: ./openFrameworks/scripts/msys2
        run: ./install_dependencies.sh
