name: windows
on:
  push:
    branches:
      - windows-workflow
jobs:
  compile:
    runs-on: windows-latest
    env:
      OF_URL: https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_msys264_release.zip
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: Get-ExecutionPolicy
      - run: $HOME
      - run: $Host
      - run: $IsWindows
      - run: $PSHOME
      - run: $PWD
      - run: $Env:OF_URL
      - run: mkdir ../.ofxPiMapper
      - run: cp ./* ../.ofxPiMapper/
      - run: curl --help
      - run: curl --location --progress-bar --output openFrameworks.zip https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_msys264_release.zip
      - run: pwd && ls
      - run: unzip openFrameworks.zip
