name: windows
on:
  push:
    branches:
      - windows-workflow
jobs:
  compile:
    runs-on: windows-latest
    env:
      OF_URL: https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_msys264_release.zip
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Move files to temporary location
        run: pwd && whoami
      - name: Download and unzip openFrameworks
        run: |
          curl --help
          echo ${OF_URL}
