name: windows
on:
  push:
    branches:
      - windows-workflow
jobs:
  compile:
    runs-on: windows-latest
    env:
      OF_URL: https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_msys264_release.zip
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Move files to temporary location
        run: |
          New-Item -Path "../" -Name "Temp" -ItemType "directory"
          Move-Item -Path "./*" -Destination "../Temp/"
      - run: curl --help
      - run: curl --location --progress-bar $Env:OF_URL
      - run: ls
      - run: unzip openFrameworks.zip
